### PR TITLE
Clarifying current project status.

### PR DESCRIPTION
**Pull request by MoffD**
Just wanted to add some information for people so they know it's not finished. :+1:

### CODE REVIEW

**Comment by groteworld** [comment]
I thought I clarified that in the README but this definitely helps. Thanks!

**Comment by MoffD** [comment]
No problem, I'm happy someone's implementing the esoteric programming languages ;)

**Comment by groteworld** [comment]
It's failing for Travis but I know this isn't the cause. I can't merge from my phone because of this but I'll merge as soon as I get to a computer.

Thanks for the support. I just got some free time so I'll look back at this and finish my learning.

**Comment by MoffD** [comment]
Thanks, you did notice the extra pokeball file right?

**Comment by groteworld** [comment]
:+1: Totally!

**Pull request merged**
